### ISSUE TITLE
Single threaded executor is used for callbacks of two nodes

### ISSUE THREAD

**Issue by sayali-purdue** [jmguerreroh/ros2_computer_vision#1]
In file [cv_pcl_node.cpp](src/computer_vision/src/cv_pcl_node.cpp), single-threaded executor is used to process callbacks of two ROS nodes: [cv_node](https://github.com/jmguerreroh/ros2_computer_vision/blob/c588bda5250ff77181a3fe777dfcc774683a93de/src/computer_vision/src/cv_pcl_node.cpp#L157) and [pcl_node](https://github.com/jmguerreroh/ros2_computer_vision/blob/c588bda5250ff77181a3fe777dfcc774683a93de/src/computer_vision/src/cv_pcl_node.cpp#L158). That means single thread is responsible for executing callbacks from two different callback groups (one default callback group per node). As discussed in ROS documentation, callbacks from different callback groups can execute in parallel. However due to single thread, the callbacks of the two nodes can not execute in parallel. Using a multi-threaded executor would be more efficient for this use case.

I would appreciate to hear your thoughts on this.

**Comment by jmguerreroh** [comment]
Hi @sayali-purdue,

Indeed, when using a single executor, callbacks may even contain unsynchronized information.

This project was carried out some time ago with the release of ROS Galactic, so it is somewhat outdated. The project was split into two independent parts: the simulator [1] and the image processing [2] using message synchronization. You can find these repositories here: 

[1] https://github.com/jmguerreroh/tiago_simulator.git
[2] https://github.com/jmguerreroh/computer_vision


I hope this helps. Thank you!

**Comment by User-o2** [comment]
> Hi [@sayali-purdue](https://github.com/sayali-purdue),  你好，
> 
> Indeed, when using a single executor, callbacks may even contain unsynchronized information.的确，当使用单个执行器时，回调甚至可能包含未同步的信息。
> 
> This project was carried out some time ago with the release of ROS Galactic, so it is somewhat outdated. The project was split into two independent parts: the simulator [1] and the image processing [2] using message synchronization. You can find these repositories here:这个项目是在 ROS Galactic 发布后进行的，所以有些过时了。该项目被分为两个独立的部分：模拟器[1]和基于消息同步的图像处理[2]。您可以在以下位置找到这些仓库：
> 
> [1] https://github.com/jmguerreroh/tiago_simulator.git [2] https://github.com/jmguerreroh/computer_vision
> 
> I hope this helps. Thank you!希望这能帮到您。谢谢！

May I inquire if the two parts of the repository linked above are complete? Can it be run if I pull it down? Thank you

**Comment by jmguerreroh** [comment]
> May I inquire if the two parts of the repository linked above are complete? Can it be run if I pull it down? Thank you

Hi  @User-o2,

[1] The CI is passing in Humble, but it depends on third-party packages from PAL, so I can't guarantee everything is fully functional. Also, please note that this robot won't work on Jazzy, as the repository uses Gazebo Classic. If you want the latest updates, please use this version [3].

[2] This is working properly.

Best regards.

[1] https://github.com/jmguerreroh/tiago_simulator.git 
[2] https://github.com/jmguerreroh/computer_vision
[3] https://github.com/Tiago-Harmonic/tiago_harmonic

**Comment by User-o2** [comment]
> > May I inquire if the two parts of the repository linked above are complete? Can it be run if I pull it down? Thank you我可以询问上面链接的仓库的两个部分是否完整吗？如果下载下来，可以运行吗？谢谢
> 
> Hi [@User-o2](https://github.com/User-o2),  你好，
> 
> [1] The CI is passing in Humble, but it depends on third-party packages from PAL, so I can't guarantee everything is fully functional. Also, please note that this robot won't work on Jazzy, as the repository uses Gazebo Classic. If you want the latest updates, please use this version [3].[1] 在 Humble 中 CI 正在通过，但它依赖于来自 PAL 的第三方包，因此我无法保证所有功能都完全可用。另外，请注意，这个机器人不能在 Jazzy 上工作，因为仓库使用 Gazebo Classic。如果您想获取最新更新，请使用此版本[3]。
> 
> [2] This is working properly.[2] 正常工作。
> 
> Best regards.  最好的问候
> 
> [1] https://github.com/jmguerreroh/tiago_simulator.git [2] https://github.com/jmguerreroh/computer_vision [3] https://github.com/Tiago-Harmonic/tiago_harmonic

Thanks.
